[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "javascript>=1!1.2.2",
    "pillow>=11.1.0",
    "pytz>=2025.1",
    "requests>=2.32.3",
    "twilio>=9.4.6",
]
